spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: moochi
    password: test
    virtual-host: test

  redis:
    host: 192.168.30.221
    port: 6379

server:
  port: 8090
logging:
  level:
    org.springframework.amqp.rabbit: ERROR
