version: '3.9'
services:
  dragonfly:
    image: 'ghcr.io/dragonflydb/dragonfly:v0.11.0-ubuntu'
    container_name: dragonfly
    hostname: dragonfly
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    volumes:
      - "${DRAGONFLY_HOME}/data:/data"
